name: flutter_study
description: "Praticando Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_modular: ^6.3.2
  mocktail: ^1.0.2
  rename_app: ^1.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/lock_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
